// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEu-dlQWQeorsUW6nUK_SAheTLShZLSYg',
    appId: '1:999037488630:android:39eec7996d231a10510bd7',
    messagingSenderId: '999037488630',
    projectId: 'quora-clone-4e1e6',
    storageBucket: 'quora-clone-4e1e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbcMoP_HwUuoCHFEScOhoXwQxeLpi4Mvk',
    appId: '1:999037488630:ios:6fb1980dbc2b69ef510bd7',
    messagingSenderId: '999037488630',
    projectId: 'quora-clone-4e1e6',
    storageBucket: 'quora-clone-4e1e6.appspot.com',
    iosBundleId: 'com.example.quoraClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbcMoP_HwUuoCHFEScOhoXwQxeLpi4Mvk',
    appId: '1:999037488630:ios:6fb1980dbc2b69ef510bd7',
    messagingSenderId: '999037488630',
    projectId: 'quora-clone-4e1e6',
    storageBucket: 'quora-clone-4e1e6.appspot.com',
    iosBundleId: 'com.example.quoraClone',
  );
}
